"""Stage the derived literature dataset + coder bundle for a Zenodo release.

Phase 4 of the D1.2 exploitation plan: collect the derived artifacts into
``notebooks/release_payload/`` and write ``metadata/zenodo_params.json`` so
the existing upload workflow can publish them to the ``biofairnet`` community
with proper provenance.

Deliberate safety/FAIR choices:

- ``use_sandbox`` defaults to **True** — after the manual review, flip it to
  False in ``metadata/zenodo_params.json`` (or via the workflow-dispatch
  input) for the production DOI.
- License is **CC-BY-4.0**, not MIT: the payload is a derivative of the
  CC-BY-4.0 datasets by Guerreschi, Lomuscio & Albanese, so attribution must
  travel with it (it is embedded in the description and the
  ``related_dois`` → ``isDerivedFrom`` links).
- Staging only: this module never commits, tags, or calls the Zenodo API.
  Triggering the upload stays a manual, reviewable step (Actions UI or a
  ``zenodo-ul-*`` tag).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from helper.upload_collector import prepare_release_payload
from helper.utils import find_repo_root, save_run_log

from .literature import D12_FULL_LIST_DOI, D12_CODEBOOK_DOI

#: Software concept DOI of the GreenInformationFactory prototype.
GIF_SOFTWARE_DOI = "10.5281/zenodo.18428335"


def default_release_params() -> Dict[str, object]:
    """Zenodo deposition metadata for the derived literature release."""
    return {
        "use_sandbox": True,  # flip to False only after the manual review
        "community": "biofairnet",
        "license": "cc-by-4.0",
        "upload_type": "dataset",
        "title": ("GreenInformationFactory – WP1/D1.2 Literature Corpus: "
                  "Tidy Data, Hotspot Analytics & ML-Assisted Coding Models"),
        "description": (
            "Derived FAIR release generated by the GreenInformationFactory pipeline "
            "(gif.literature / gif.lit_analytics / gif.lit_ml) from the BioFairNet "
            "WP1/D1.2 literature datasets. Contains: (1) tidy corpus tables "
            "(papers.csv: 366 papers with English snake_case columns; codes_long.csv: "
            "manual codes in long format; papers_coded.csv: joined wide table), "
            "(2) descriptive hotspot analytics (code frequencies by sector, country "
            "mentions, geographic levels, publication years, barrier-driver "
            "co-occurrence; tables and figures), and (3) TF-IDF text-classification "
            "models trained on the manual codes for pre-coding future literature "
            "batches (literature_coder.pkl with cross-validated evaluation tables; "
            "screening aid, not a replacement for manual coding). "
            "Source data (CC-BY-4.0) by Guerreschi, Lomuscio & Albanese: full list "
            f"{D12_FULL_LIST_DOI}, codebook {D12_CODEBOOK_DOI}. "
            f"Pipeline software: {GIF_SOFTWARE_DOI}."
        ),
        "creators": [
            {
                "name": "Rosnitschek, Tobias",
                "affiliation": "University of Bayreuth",
                "orcid": "0000-0002-4876-2536",
            }
        ],
        "keywords": [
            "FAIR", "literature analysis", "circular economy",
            "machine learning", "text classification", "bioeconomy",
        ],
        # isDerivedFrom links written into the deposition by the workflow
        "related_dois": [D12_FULL_LIST_DOI, D12_CODEBOOK_DOI],
        "payload_dir": "notebooks/release_payload",
    }


def collect_release_files(repo_root: Path) -> Dict[str, List[str]]:
    """Enumerate payload files as repo-relative paths, grouped for the collector.

    Only files that exist are returned; the caller sees what is missing via
    the collector's report.
    """
    lit_processed = repo_root / "data" / "processed" / "literature"
    lit_results = repo_root / "data" / "results" / "literature"

    files = sorted(str(p.relative_to(repo_root)) for p in lit_processed.glob("*.csv"))
    results = sorted(str(p.relative_to(repo_root)) for p in lit_results.glob("lit_*.*"))
    models = ["notebooks/models/literature_coder.pkl"]
    return {"files": files, "results": results, "models": models}


def stage_literature_release(
    repo_root: Optional[Path] = None,
    *,
    use_sandbox: bool = True,
    log: bool = True,
) -> Dict[str, object]:
    """Collect the payload and write the release params (staging only).

    Returns a report with the payload listing, missing files, and the params
    path. Does **not** commit, tag, or upload — trigger the workflow manually
    after review.
    """
    repo_root = repo_root or find_repo_root()
    groups = collect_release_files(repo_root)

    collected = prepare_release_payload(
        files=groups["files"],
        results=groups["results"],
        models=groups["models"],
        require_all=False,
        repo_root=repo_root,
    )

    params = default_release_params()
    params["use_sandbox"] = bool(use_sandbox)
    params_path = repo_root / "metadata" / "zenodo_params.json"
    params_path.write_text(json.dumps(params, indent=2, ensure_ascii=False),
                           encoding="utf-8")

    report: Dict[str, object] = {
        "payload_dir": str(collected["payload_dir"]),
        "copied": [p.name for p in collected["copied"]],
        "missing": [str(m) for m in collected["missing"]],
        "params_path": str(params_path),
        "use_sandbox": params["use_sandbox"],
        "license": params["license"],
        "related_dois": params["related_dois"],
        "next_steps": [
            "Review the payload listing and the analytics outputs.",
            "Commit payload + params, then trigger the upload workflow "
            "(GitHub Actions UI or a zenodo-ul-* tag) — sandbox first.",
            "After checking the sandbox record, set use_sandbox=false in "
            "metadata/zenodo_params.json and trigger again for the DOI.",
        ],
    }
    if log:
        try:
            save_run_log("literature_release_staged", report, repo_root=repo_root)
        except Exception as exc:
            print(f"⚠️ Could not write run log: {exc}")
    return report
